version: '3'
services:
  api:
    command: bundle exec rails server --port $API_PORT -b 0.0.0.0
    build:
      context: ./api
    env_file:
      - api.env
      - api.local.env
    volumes:
      - ./api:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "${API_PORT}:${API_PORT}"
volumes:
  bundle_cache:
